### ISSUE TITLE
Support for jgrossi/corcel 3 planned?

### ISSUE THREAD

**Issue by lamalamaMark** [tbruckmaier/corcel-acf#6]
Thanks for all the work for this repository until now. I was wondering if you're planning to support jgrossi/corcel 3.*.

If not, can we assist and do you already investigated what kind of changes are necessary?

**Comment by tbruckmaier** [comment]
Hi, yes I am working on a page right now which will be based on laravel 6 (and therefore corcel 3.* as well i guess). I have not yet investigated if laravel or corcel have changed a lot, just seen that the array helpers like `array_get` have to be replaced
So the support will come, but i will also accept pull requests dealing with that

**Comment by jfw7** [comment]
https://github.com/people-designs/corcel-acf/

I've started a fork for L7 support (forking from @christian-thomas)

**Comment by mindfullsilence** [comment]
@jfw7 your branch could save my project! Any chance you could look into why it fails when using [API Resource](https://laravel.com/docs/7.x/eloquent-resources) classes with the models? 

```
BadMethodCallException
Call to undefined method Tbruckmaier\Corcelacf\Models\Post::mapInto()
```

When removing the resource class and just returning the Model, a separate issue is that my relationships aren't actual field values, they are the acf field object. Here's an example:

```php
class Asset extends Post
{
    use AcfTrait;

    protected $postType = 'asset';

    public function assetGroup() {
        return $this->hasAcf('asset_group');
    }
}
```

```php
class Asset extends Post
{
    use AcfTrait;

    protected $postType = 'asset';

    public function assetGroup() {
        return $this->hasAcf('asset_group');
    }
}
```


This fails with the aforementioned BadMethodCallException
```php
public function index() {
    $assets = AssetGroup::all()->load('assets');
    return \App\Http\Resources\AssetGroup::collection($assets);
}
```

This gives back the asset groups, with a key of `assets` that contains the acf field instead of its values:
```php
public function index() {
    $assets = AssetGroup::all()->load('assets');
    return response()->json($assets);
}
```

Example output from above (simplified for brevity):
```json
[
    {
        "ID": 67,
        "post_title": "Stoliknaya",
        "post_type": "assetgroup",
        "assets": {
            "ID": 38,
            "post_title": "Assets",
            "post_type": "acf-field",
            "post_name": "field_5eea44a732cd4",
        }
    }
]
```

"assets" here should come back as an array of "asset" posts, but is instead coming back as a single field object. I'm not sure if the two issues are related. Any ideas?

**Comment by jfw7** [comment]
I'm not sure how much I can help—I'll admit that I'm confused by the distinction between the various ways of calling ACF (methods/properties, with `acf` object or `acf_` prefix, etc.). The main difference from my code that's working (for now) is that I call `addAcfRelations()` rather than `hasAcf()`:

```php
class Session extends Post
{
    use AcfTrait;

    public static function booting()
    {
        static::addAcfRelations(['content_players']);
    }
```

`content_players` is an ACF repeater of repeaters, so I call it like this from a shortcode:


```php
    public function render(ShortcodeInterface $shortcode)
    {
        $parameters = $shortcode->getParameters();
        $index = intval($parameters['index'] ?? 1) - 1;
        $player = $this->post->acf->content_players->get($index);
        // $player is a Tbruckmaier\Corcelacf\Support\RepeaterLayout object
        if ($player) {
            // $player->content_player_screens is a Collection of RepeaterLayout objects
            $parameters['screens'] = $player->content_player_screens->reduce(
                function ($screens, $screen) {
                    /// do stuff with screens...
                },
                []
            );
        }
        // return view, etc...
    }
}
```

Let me see if I can figure out why this breaks with `hasAcf()`. I don't really remember how I arrived at this solution or whether it's particularly efficient, but my L7 branch is giving me the same query count as my L5 branch so it's hopefully consistent :)

**Comment by jfw7** [comment]
I think also the `->value` distinction is in play somewhere... I don't understand the layers here, I've just obviously tried various iterations until something worked

**Comment by mindfullsilence** [comment]
@jfw7 I went ahead and swapped out to using the booting method, and ended up with a new exception. So I now have AssetGroup like so:

```php

class AssetGroup extends Post
    use AcfTrait;

    protected $postType = 'assetgroup';

    public static function booting()
    {
        static::addAcfRelations(['assets']);
    }
}
```

and my controller I simplified to this:

```php
public function index() {
  $assetGroups = AssetGroups::all();

  return response()->json($assetGroups);
}
```

This throws 
```
BadMethodCallException
Call to undefined method App\Database\AssetGroup::resolveRelationUsing()
```

I'm starting to think maybe this has to do with something that has changed in core Laravel regarding eloquent in recent L7 minors. Can you tell me what Laravel framework version your project is running?

**Comment by jfw7** [comment]
Oh, good point. I'm on 7.16. It looks like `resolveRelationUsing()` is a relatively new part of L7 from 3 or 4 weeks ago.

**Comment by mindfullsilence** [comment]
Nice, that definitely made progress! I'm no longer getting exceptions, but still getting the field itself rather than the post it relates to. If I set my resource to the following:

```php
class AssetGroup extends JsonResource
{
    public function toArray($request)
    {
        $assets = $this->acf_assets->first();

        return [
            'id' => $this->ID,
            'post_title' => $this->post_title,
            'post_type' => $this->post_type,
            'assets' => $this->acf_assets->internal_value
        ];
    }
}
```

The result ends up being the following:

```json
{
  "data": [
    {
      "id": 73,
      "post_title": "Ketel One",
      "post_type": "assetgroup",
      "assets": "a:1:{i:0;s:2:\"74\";}"
    }
  ]
}
```

For the "assets" key, I've tried the following and been given back the following:

```php
$this->acf_assets->internal_value // "a:1:{i:0;s:2:\"74\";}"
$this->acf_assets->value // null
$this->acf_assets // acf-field object
$this->acf->assets // null
$this->assets // "a:1:{i:0;s:2:\"74\";}"
```

**Comment by mindfullsilence** [comment]
I ended up unserializing the internal_value result and running a separate query and for now its working. But would love to work with you on a better solution - I'm expecting to very quickly have hundreds of thousands of `assets` and hundreds of `asset_groups` after launch.

**Comment by jfw7** [comment]
Happy to hear something's at least running for you! Feel free to fork or ping me with suggestions, and hopefully @tbruckmaier can work on building out some more robust L7 solutions for this awesome project.  

I don't use ACF to represent Eloquent models in this project and I'm not sure I've even ever used ACF relationships, so it's probably the case that my scrape-the-surface usage didn't run into the issues you're seeing. If I run into any solutions I'll let you know for sure.

**Comment by tbruckmaier** [comment]
Hey, just a short notice before I can test this fully, maybe it helps:

The actual magic happens in the `acf_something()` methods, which work like (and extend from) the standard laravel `HasOne` relationship.

`addAcfRelations()` and `$post->acf->...` / `$post->getAcfAttribute()` are "just" helpers, to create the relation methods and makes accessing them easier. I have used monkey patching here with the "greabock/tentacles" package, and the fork seems to use `macro` now (?).

The problems above seem to originate from the second part though, so maybe actual relations still work? You could try to create the relations manually and see if that still works:

```php
function acf_assets()
{
    return $this->hasAcf('assets'); // accesses the "assets" acf field
}
``` 

(which is the same method which `static::addAcfRelations(['assets'])` creates)

When you access that relation as a property (`dd($post->acf_assets)`), a sub class of `Tbruckmaier\Corcelacf\Models\BaseField` should be returned, for instance `Tbruckmaier\Corcelacf\Models\Image` or `Text` or whatever that field's type is. The parsed value can be accessed via `->value()`, so `$post->acf_assets->value()` should return "sample text" or a `Corcel\Model\Attachment`.

And some further details if it doesn't work: the `Tbruckmaier\Corcelacf\Models\BaseField` classes have two properties set: `$data` and `$localKey`

`$data` holds the _complete_ meta data of the post (so all acf fields of a post contain the same data here). `$localKey` points to the field's relevant part. The method `interval_value()` returns the _unparsed_ content for this field, e.g. the (string) value of `$data[$localKey]`. `value()` finally returns a suitable sub class of `Tbruckmaier\Corcelacf\Models\BaseField`, which parses the `internal_value` into a suitable type (a string or an `Attachment` class)

**Comment by jfw7** [comment]
> I have used monkey patching here with the "greabock/tentacles" package, and the fork seems to use `macro` now (?).

The fork I forked from used `macro()` but it wasn't working for me, so I saw something about `resolveRelationUsing()` and it seemed promising https://github.com/people-designs/corcel-acf/commit/b127e164a14fc28ef4aafcee68e412dc4c986f3f

**Comment by tbruckmaier** [comment]
Hm, both seems to be ok as far as I can see. Can you make the relations work if you specify them manually like above?

```php
function acf_assets()
{
    return $this->hasAcf('assets'); // accesses the "assets" acf field
}
```

**Comment by mindfullsilence** [comment]
I tried both with `acf_*` methods as well as the `booted`method, both returned the field object

**Comment by tbruckmaier** [comment]
And is the field object properly filled? What happens if you access the field objects `value()` method (`$post->acf_assets->value()`)?

If that does not work, could you post the field object itself (via `dd()` or `var_export()`). Then we need to see if `$data` and `$localKey` are properly filled. But beware, these dumps might contain the post's complete meta data, maybe you have some sensitive information in there ;)

**Comment by tbruckmaier** [comment]
I have just tagged a new release which should work with laravel 6 & 7 (and possibly upcoming versions too).

The issue was with the monkey patching: both `macro()` and `resolveRelationUsing()` seem to work a bit different than the original library, thats what caused your issues I guess. I have replaced the original library with a fork which supports newer laravel too, and now everything seems to work again.

Could you test and provide me feedback? I have just tested it really quick with a sample installation, but it would be nice to hear if the more complicated field setups work too

I have also changed the composer requirements to support any newer versions of laravel & phpunit , so there is no need to update for every new release.

**Comment by jfw7** [comment]
@tbruckmaier The new release seems to work for my use case! Sorry for not getting around to this sooner. Thanks!

**Comment by tbruckmaier** [comment]
No worries, glad it works!
